### ISSUE TITLE
임유나 todo

### ISSUE THREAD

**Issue by iyn000** [Woonghyeon13/ggamedori#18]
### **~04.14**
>  ### 마이페이지

>
- [x] 리스트 작동 확인
- [x] 상단 카운트 작동 확인
- [x] 검색기능 작동 확인

> ### 메인
- [x] 화면 디자인 수정

**Comment by iyn000** [comment]
### **~04.21**
>  ### 마이페이지

- [x] 각 링크 바로가기 달아두기
- [x] 오류 수정

> ### 등급업
- [ ] 결제완료후 누적적립금에 따라 등급업 코드작성

**Comment by iyn000** [comment]
### **~04.25**
>  ### 상품리스트

- [] 조건별 리스트 정렬

> ### **~04.28**
- [ ] PPT제작
